#!/bin/sh
#
# @name ZMR250 Racer
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Anton Matosov <anton.matosov@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

if [ $AUTOCNF = yes ]
then
	param set CBRK_IO_SAFETY 22027
	param set GPS_1_CONFIG  0
	param set SYS_USE_IO 0
	param set DSHOT_CONFIG  300

	param set FAILSAFE 100

	param set MC_ROLL_P  40
	param set MC_ROLLRATE_P 0.05
	param set MC_ROLLRATE_I 0.055
	param set MC_ROLLRATE_D 0.02
	param set MC_RR_INT_LIM 0.2

	param set MC_PITCH_P 40
	param set MC_PITCHRATE_P 0.05
	param set MC_PITCHRATE_I 0.04
	param set MC_PITCHRATE_D 0.02
	param set MC_PR_INT_LIM 0.2

	param set MC_YAW_P 1
	param set MC_YAWRATE_P 0.15
	param set MC_YAWRATE_I 0.11
	param set MC_YAWRATE_D 0.012

	param set MC_ACRO_R_MAX 1000
	param set MC_ACRO_P_MAX 1000
	param set MC_ACRO_Y_MAX 1000

	# param set NAV_RCL_ACT 6 # Lockdown

	param set PWM_MIN 1075
	param set PWM_RATE 400
	param set PWM_DISARMED 900
fi
