#!/bin/sh
#
# @name Solo
#
# @type Quadrotor
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.1
	param set MC_ROLLRATE_P 0.1

	param set MNT_MODE_IN -1
	param set MNT_MODE_OUT 0
fi

set MIXER quad_x
