#!/bin/sh
#
# @name mav_isir SITL
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4

sh /etc/init.d/rc.mc_defaults
set MIXER quad_x

if [ $AUTOCNF = yes ]
then
	# Power Parameters
	param set BAT_N_CELLS 2

	# EKF2 parameters
	param set EKF2_AID_MASK 1
	param set EKF2_HGT_MODE 1
	param set EKF2_IMU_POS_X 0.02
	param set EKF2_GPS_MASK 7
	param set EKF2_GPS_POS_X 0.055
	param set EKF2_GPS_POS_Z -0.15
	param set EKF2_OF_POS_Z 0.06
	param set EKF2_RNG_POS_X 0.02
	param set EKF2_RNG_POS_Z 0.07
	param set EKF2_REQ_HDRIFT 0.3
	param set EKF2_REQ_SACC 1
	param set EKF2_REQ_VDRIFT 0.3
	param set EKF2_RNG_AID 1
	param set EKF2_RNG_A_HMAX 12
	param set EKF2_RNG_A_VMAX 2
	param set EKF2_RNG_POS_X 0.02
	param set EKF2_RNG_POS_Z 0.07

	# Position Control Tuning
	param set MPC_MAN_Y_MODE 1
	param set MPC_MAN_Y_A_MAX 2
	param set MPC_MAN_NED_SET 0
	param set MPC_Z_VEL_MAX_UP 3.0
	param set MPC_Z_VEL_MAX_DN 2.0
	param set MPC_MAN_TILT_MAX 20
	param set MPC_ALT_MODE 3

	# Vehicle attitude PID tuning
	param set MC_ROLL_P  2
	param set MC_ROLLRATE_P 0.2
	param set MC_ROLLRATE_I 0.005
	param set MC_ROLLRATE_D 0.01
	param set MC_RR_INT_LIM 0.1

	param set MC_PITCH_P 2
	param set MC_PITCHRATE_P 0.2
	param set MC_PITCHRATE_I 0.005
	param set MC_PITCHRATE_D 0.01
	param set MC_PR_INT_LIM 0.1

	param set MC_YAW_P 1
	param set MC_YAWRATE_P 0.2
	param set MC_YAWRATE_I 0.1
	param set MC_YAWRATE_D 0.0
	param set MC_YR_INT_LIM 0.3

	param set MC_ACRO_R_MAX 1000
	param set MC_ACRO_P_MAX 1000
	param set MC_ACRO_Y_MAX 1000

	# Sensors Parameters
	param set SENS_BOARD_ROT 0
	param set SENS_FLOW_MAXHGT 12
	param set SENS_FLOW_MINHGT 0.3
	param set SENS_FLOW_ROT 6

	# Logging Parameters
	param set SDLOG_PROFILE 131

fi
# Need to set all 8 channels
set PWM_OUT 1234
